"""Tests for CodeGenerator."""

from __future__ import annotations

import importlib.util
import typing
from pathlib import Path

import pytest
from godoo.introspection.codegen import CodeGenerator, _model_to_classname, _model_to_filename
from godoo.introspection.types import FieldSchema, ModelSchema


def _schema(model_name: str = "res.partner", **fields: FieldSchema) -> ModelSchema:
    """Build a minimal ModelSchema for testing."""
    return ModelSchema(name=model_name, fields=dict(fields))


def _char_field(fname: str = "name") -> FieldSchema:
    return FieldSchema(name=fname, ttype="char")


def _selection_field(fname: str = "state") -> FieldSchema:
    return FieldSchema(
        name=fname,
        ttype="selection",
        selection=[("draft", "Draft"), ("done", "Done")],
    )


def test_generate_header() -> None:
    gen = CodeGenerator(None)  # type: ignore[arg-type]
    schema = _schema()
    result = gen.generate(schema)
    assert "AUTOGENERATED" in result
    assert "from typing import" in result


def test_generate_class_name() -> None:
    gen = CodeGenerator(None)  # type: ignore[arg-type]
    schema = _schema("res.partner")
    result = gen.generate(schema)
    assert "class ResPartner(TypedDict, total=False):" in result


def test_generate_id_required() -> None:
    gen = CodeGenerator(None)  # type: ignore[arg-type]
    schema = _schema()
    result = gen.generate(schema)
    assert "id: Required[int]" in result


def test_generate_field_notrequired() -> None:
    gen = CodeGenerator(None)  # type: ignore[arg-type]
    schema = _schema("res.partner", name=_char_field("name"))
    result = gen.generate(schema)
    assert "name: NotRequired[" in result


def test_generate_field_meta_import() -> None:
    gen = CodeGenerator(None)  # type: ignore[arg-type]
    schema = _schema()
    result = gen.generate(schema)
    # Must be a RUNTIME import, not under TYPE_CHECKING
    assert "from godoo.introspection.markers import FieldMeta" in result
    assert "TYPE_CHECKING" not in result


def test_generate_selection_literal() -> None:
    gen = CodeGenerator(None)  # type: ignore[arg-type]
    schema = _schema("res.partner", state=_selection_field("state"))
    result = gen.generate(schema)
    assert "Literal[" in result


def test_generate_valid_python() -> None:
    gen = CodeGenerator(None)  # type: ignore[arg-type]
    schema = _schema(
        "res.partner",
        name=_char_field("name"),
        state=_selection_field("state"),
    )
    result = gen.generate(schema)
    # Must compile without SyntaxError
    compile(result, "<string>", "exec")


def test_generate_get_type_hints_round_trip(tmp_path: Path) -> None:
    """Verify generated code survives get_type_hints extraction.

    Uses importlib to load the generated .py file so that class annotations
    are resolved in a proper module context (avoids Python 3.14 exec/ForwardRef
    module-binding issue when the calling module uses from __future__ import annotations).
    """
    gen = CodeGenerator(None)  # type: ignore[arg-type]
    schema = _schema("res.partner", name=_char_field("name"))
    result = gen.generate(schema)
    # Write to a temp file and import it properly via importlib
    mod_file = tmp_path / "res_partner.py"
    mod_file.write_text(result, encoding="utf-8")
    spec = importlib.util.spec_from_file_location("res_partner_test", mod_file)
    assert spec is not None and spec.loader is not None
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)  # type: ignore[union-attr]
    cls = mod.ResPartner
    hints = typing.get_type_hints(cls, include_extras=True)
    assert "id" in hints
    # id should have Required origin
    assert typing.get_origin(hints["id"]) is typing.Required


def test_model_to_classname() -> None:
    assert _model_to_classname("res.partner") == "ResPartner"
    assert _model_to_classname("account.move.line") == "AccountMoveLine"
    assert _model_to_classname("ir.model.fields") == "IrModelFields"


def test_model_to_filename() -> None:
    assert _model_to_filename("res.partner") == "res_partner.py"
    assert _model_to_filename("account.move.line") == "account_move_line.py"


def test_write_creates_files(tmp_path: Path) -> None:
    gen = CodeGenerator(None)  # type: ignore[arg-type]
    schema = _schema("res.partner", name=_char_field("name"))
    gen.write([schema], tmp_path)
    assert (tmp_path / "res_partner.py").exists()
    content = (tmp_path / "res_partner.py").read_text()
    assert "ResPartner" in content


def test_write_creates_init(tmp_path: Path) -> None:
    gen = CodeGenerator(None)  # type: ignore[arg-type]
    schema = _schema("res.partner", name=_char_field("name"))
    gen.write([schema], tmp_path)
    init_file = tmp_path / "__init__.py"
    assert init_file.exists()
    content = init_file.read_text()
    assert "ResPartner" in content


def test_write_invalid_dir_raises(tmp_path: Path) -> None:
    gen = CodeGenerator(None)  # type: ignore[arg-type]
    schema = _schema()
    with pytest.raises(ValueError, match="not a directory"):
        gen.write([schema], Path("/nonexistent/path"))


def test_generate_empty_schema_pass() -> None:
    gen = CodeGenerator(None)  # type: ignore[arg-type]
    # Schema with no fields — body must contain 'pass' (id is always emitted, so
    # a schema with only id-equivalent coverage → use an empty fields dict)
    schema = ModelSchema(name="res.empty", fields={})
    result = gen.generate(schema)
    assert "pass" in result
