"""Tests for CodeGenerator."""

from __future__ import annotations

import typing
from pathlib import Path

import pytest

from godoo_introspection.codegen import CodeGenerator, _model_to_classname, _model_to_filename
from godoo_introspection.types import FieldSchema, ModelSchema


def _schema(name: str = "res.partner", **fields: FieldSchema) -> ModelSchema:
    """Build a minimal ModelSchema for testing."""
    return ModelSchema(name=name, fields=dict(fields))


def _char_field(fname: str = "name") -> FieldSchema:
    return FieldSchema(name=fname, ttype="char")


def _selection_field(fname: str = "state") -> FieldSchema:
    return FieldSchema(
        name=fname,
        ttype="selection",
        selection=[("draft", "Draft"), ("done", "Done")],
    )


def test_generate_header() -> None:
    gen = CodeGenerator(None)  # type: ignore[arg-type]
    schema = _schema()
    result = gen.generate(schema)
    assert result.startswith("from __future__ import annotations")
    assert "AUTOGENERATED" in result


def test_generate_class_name() -> None:
    gen = CodeGenerator(None)  # type: ignore[arg-type]
    schema = _schema("res.partner")
    result = gen.generate(schema)
    assert "class ResPartner(TypedDict, total=False):" in result


def test_generate_id_required() -> None:
    gen = CodeGenerator(None)  # type: ignore[arg-type]
    schema = _schema()
    result = gen.generate(schema)
    assert "id: Required[int]" in result


def test_generate_field_notrequired() -> None:
    gen = CodeGenerator(None)  # type: ignore[arg-type]
    schema = _schema(fields={"name": _char_field("name")})
    result = gen.generate(schema)
    assert "name: NotRequired[" in result


def test_generate_field_meta_import() -> None:
    gen = CodeGenerator(None)  # type: ignore[arg-type]
    schema = _schema()
    result = gen.generate(schema)
    # Must be a RUNTIME import, not under TYPE_CHECKING
    assert "from godoo_introspection.markers import FieldMeta" in result
    assert "TYPE_CHECKING" not in result


def test_generate_selection_literal() -> None:
    gen = CodeGenerator(None)  # type: ignore[arg-type]
    schema = _schema(fields={"state": _selection_field("state")})
    result = gen.generate(schema)
    assert "Literal[" in result


def test_generate_valid_python() -> None:
    gen = CodeGenerator(None)  # type: ignore[arg-type]
    schema = _schema(
        "res.partner",
        name=_char_field("name"),
        state=_selection_field("state"),
    )
    result = gen.generate(schema)
    # Must compile without SyntaxError
    compile(result, "<string>", "exec")


def test_generate_get_type_hints_round_trip() -> None:
    gen = CodeGenerator(None)  # type: ignore[arg-type]
    schema = _schema("res.partner", name=_char_field("name"))
    result = gen.generate(schema)
    ns: dict[str, object] = {}
    exec(compile(result, "<string>", "exec"), ns)  # noqa: S102
    cls = ns["ResPartner"]
    hints = typing.get_type_hints(cls, include_extras=True)  # type: ignore[arg-type]
    assert "id" in hints
    # id should have Required origin
    assert typing.get_origin(hints["id"]) is typing.Required


def test_model_to_classname() -> None:
    assert _model_to_classname("res.partner") == "ResPartner"
    assert _model_to_classname("account.move.line") == "AccountMoveLine"
    assert _model_to_classname("ir.model.fields") == "IrModelFields"


def test_model_to_filename() -> None:
    assert _model_to_filename("res.partner") == "res_partner.py"
    assert _model_to_filename("account.move.line") == "account_move_line.py"


def test_write_creates_files(tmp_path: Path) -> None:
    gen = CodeGenerator(None)  # type: ignore[arg-type]
    schema = _schema("res.partner", name=_char_field("name"))
    gen.write([schema], tmp_path)
    assert (tmp_path / "res_partner.py").exists()
    content = (tmp_path / "res_partner.py").read_text()
    assert "ResPartner" in content


def test_write_creates_init(tmp_path: Path) -> None:
    gen = CodeGenerator(None)  # type: ignore[arg-type]
    schema = _schema("res.partner", name=_char_field("name"))
    gen.write([schema], tmp_path)
    init_file = tmp_path / "__init__.py"
    assert init_file.exists()
    content = init_file.read_text()
    assert "ResPartner" in content


def test_write_invalid_dir_raises(tmp_path: Path) -> None:
    gen = CodeGenerator(None)  # type: ignore[arg-type]
    schema = _schema()
    with pytest.raises(ValueError, match="not a directory"):
        gen.write([schema], Path("/nonexistent/path"))


def test_generate_empty_schema_pass() -> None:
    gen = CodeGenerator(None)  # type: ignore[arg-type]
    # Schema with no fields — body must contain 'pass' (id is always emitted, so
    # a schema with only id-equivalent coverage → use an empty fields dict)
    schema = ModelSchema(name="res.empty", fields={})
    result = gen.generate(schema)
    assert "pass" in result
